# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 31 Oct 2007 01:29:40 +0100
*	@Membres	16
*	@ALL	1
*	@Moderateurs	16
*	@Membres%20developpement%20%2d%20programmation	16
*	@Membres%20projet%20Livre%20MUL	16
*	@Membres%20projet%20Association%20MUL	16
*	@Membres%20projet%20Livre%20%2b%20Association%20MUL	16
*	@Organisation%20CdB	16
*	@Organisation%20CdB%20et%20Developpement%20%2d%20programmation	16
*	@Jury%20concours%20photo%20impair	16
accueil	@ALL	1
accueil_du_wiki	@ALL	1
faq_de_la_randonnee_legere_mul	@ALL	1
guide:*	@Membres	1
liens_de_la_randonnee_legere	@ALL	1
liens_de_la_randonnee_legere	@Moderateurs	2
livre:*	@ALL	0
livre:*	@Membres%20projet%20Livre%20MUL	16
livre:*	@Membres%20projet%20Livre%20%2b%20Association%20MUL	16
sidebar	@ALL	1
*	@Jury%20concours%20photo%20pair	16
*	@Jury%20concours%20photo%20pair%20et%20impair	16
