<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings 
 * Auto-generated by config plugin 
 * Run for user: oli_v_ier
 * Date: Mon, 08 Nov 2010 22:19:59 +0100
 */

$conf['title'] = 'Randonner leger ou ultra-léger, le site des MUL';
$conf['start'] = 'accueil_du_wiki';
$conf['lang'] = 'fr';
$conf['template'] = 'RL';
$conf['recent'] = 100;
$conf['breadcrumbs'] = 0;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['sitemap'] = 3;
$conf['plugin']['sidebarng']['order'] = 'main,toolbox,rechwiki';
$conf['plugin']['sidebarng']['content'] = 'main,rechwiki';

// end auto-generated content
